
package com.honganwei.common.ws.dreamInfo.com.gpsso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DreamSoap", targetNamespace = "http://gpsso.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DreamSoap {


    /**
     * ��������ιؼ��֣����磺���ˡ����ѡ����㣩
     * 
     * @param dream
     * @return
     *     returns com.gpsso.SearchDreamInfoResponse.SearchDreamInfoResult
     */
    @WebMethod(operationName = "SearchDreamInfo", action = "http://gpsso.com/SearchDreamInfo")
    @WebResult(name = "SearchDreamInfoResult", targetNamespace = "http://gpsso.com/")
    @RequestWrapper(localName = "SearchDreamInfo", targetNamespace = "http://gpsso.com/", className = "com.gpsso.SearchDreamInfo")
    @ResponseWrapper(localName = "SearchDreamInfoResponse", targetNamespace = "http://gpsso.com/", className = "com.gpsso.SearchDreamInfoResponse")
    public com.honganwei.common.ws.dreamInfo.com.gpsso.SearchDreamInfoResponse.SearchDreamInfoResult searchDreamInfo(
        @WebParam(name = "Dream", targetNamespace = "http://gpsso.com/")
        String dream);
}
