
package com.honganwei.common.ws.express.com.gpsso;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KuaidiSoap", targetNamespace = "http://gpsso.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KuaidiSoap {


    /**
     * ��ݲ�ѯ��֧����ͨ,��ͨ,Բͨ,˳��,EMS,�ϴ�,����,��ͨ,լ����,�°��
     * 
     * @param orderNo
     * @param compay
     * @return
     *     returns com.gpsso.KuaidiQueryResponse.KuaidiQueryResult
     */
    @WebMethod(operationName = "KuaidiQuery", action = "http://gpsso.com/KuaidiQuery")
    @WebResult(name = "KuaidiQueryResult", targetNamespace = "http://gpsso.com/")
    @RequestWrapper(localName = "KuaidiQuery", targetNamespace = "http://gpsso.com/", className = "com.gpsso.KuaidiQuery")
    @ResponseWrapper(localName = "KuaidiQueryResponse", targetNamespace = "http://gpsso.com/", className = "com.gpsso.KuaidiQueryResponse")
    public com.honganwei.common.ws.express.com.gpsso.KuaidiQueryResponse.KuaidiQueryResult kuaidiQuery(
        @WebParam(name = "Compay", targetNamespace = "http://gpsso.com/")
        String compay,
        @WebParam(name = "OrderNo", targetNamespace = "http://gpsso.com/")
        String orderNo);

}
