
package com.honganwei.common.ws.express.com.gpsso;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * <b>��ӭ���ʣ�<a href='http://www.gpsso.com'>www.gpsso.com</a>��лл���֧�֣�</b>
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Kuaidi", targetNamespace = "http://gpsso.com/", wsdlLocation = "http://www.gpsso.com/webservice/kuaidi/kuaidi.asmx?wsdl")
public class Kuaidi
    extends Service
{

    private final static URL KUAIDI_WSDL_LOCATION;
    private final static WebServiceException KUAIDI_EXCEPTION;
    private final static QName KUAIDI_QNAME = new QName("http://gpsso.com/", "Kuaidi");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.gpsso.com/webservice/kuaidi/kuaidi.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        KUAIDI_WSDL_LOCATION = url;
        KUAIDI_EXCEPTION = e;
    }

    public Kuaidi() {
        super(__getWsdlLocation(), KUAIDI_QNAME);
    }

    public Kuaidi(WebServiceFeature... features) {
        super(__getWsdlLocation(), KUAIDI_QNAME, features);
    }

    public Kuaidi(URL wsdlLocation) {
        super(wsdlLocation, KUAIDI_QNAME);
    }

    public Kuaidi(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, KUAIDI_QNAME, features);
    }

    public Kuaidi(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Kuaidi(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KuaidiSoap
     */
    @WebEndpoint(name = "KuaidiSoap")
    public KuaidiSoap getKuaidiSoap() {
        return super.getPort(new QName("http://gpsso.com/", "KuaidiSoap"), KuaidiSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KuaidiSoap
     */
    @WebEndpoint(name = "KuaidiSoap")
    public KuaidiSoap getKuaidiSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://gpsso.com/", "KuaidiSoap"), KuaidiSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (KUAIDI_EXCEPTION!= null) {
            throw KUAIDI_EXCEPTION;
        }
        return KUAIDI_WSDL_LOCATION;
    }

}
